cmake_minimum_required(VERSION 3.21)
project(QMarkdownInstalledConsumer LANGUAGES CXX)
set(QMARKDOWN_REQUEST_VERSION "1.0" CACHE STRING "Requested package version")
option(QMARKDOWN_REQUEST_EXACT "Require exact package version" OFF)
if(QMARKDOWN_REQUEST_EXACT)
    find_package(QMarkdown ${QMARKDOWN_REQUEST_VERSION} EXACT CONFIG REQUIRED)
else()
    find_package(QMarkdown ${QMARKDOWN_REQUEST_VERSION} CONFIG REQUIRED)
endif()
find_package(Qt6 6.8 REQUIRED COMPONENTS Test)
add_executable(qmarkdown-consumer main.cpp)
target_compile_features(qmarkdown-consumer PRIVATE cxx_std_17)
target_link_libraries(qmarkdown-consumer PRIVATE Qt6::Test)
option(QMARKDOWN_CONSUMER_LINK_MODULE "Link the backing library" ON)
if(QMARKDOWN_CONSUMER_LINK_MODULE)
    target_link_libraries(qmarkdown-consumer PRIVATE QMarkdown::QMarkdown)
else()
    target_link_libraries(qmarkdown-consumer PRIVATE Qt6::Quick Qt6::Qml)
endif()
if(TARGET QMarkdown::QMarkdownPlugin)
    target_link_libraries(qmarkdown-consumer PRIVATE QMarkdown::QMarkdownPlugin)
    target_compile_definitions(qmarkdown-consumer PRIVATE QMARKDOWN_STATIC)
endif()
